export const ADD_NEW_USER="ADD_NEW_USER";
export const LOGIN="LOGIN";
export const UPDATE_CURRENT_USER="UPDATE_CURRENT_USER";
export const DELETE_USER="DELETE_USER";

export const ADD_NEW_MEDICINE="ADD_NEW_MEDICINE";
export const GET_MEDICINE_FROM_SERVER="GET_MEDICINE_FROM_SERVER";
export const ADD_MEDICINE_TO_USER="ADD_MEDICINE_TO_USER";


export const ADD_DETAILS_OF_MEDICINE="ADD_DETAILS_OF_MEDICINE";
export const UPDATE_DETAILS_OF_MEDICINE="UPDATE_DETAILS_OF_MEDICINE";